### ISSUE TITLE
Design Remarks 0.1

### ISSUE THREAD

**Issue by ismailElazizi** [yjose/elazizi.com#5]
1. [x] Bring icons to the top: users wanna know more about you on the other platforms.
2.  [x] let the whole Article's box be clickable.
3. [x]  A Human first 🙌, Full Stack Web Developer 👨🏻‍💻 and OSS believers. I love working with react and ReactNative and I admire writing about my programming journey 👇👇👇.
4.  [x] I feel like the gradient on the header is a little bit messy, maybe because the photo are black and white.

**Comment by yjose** [comment]
@ismailElazizi  https://deploy-preview-7--eloquent-raman-dbad65.netlify.com/
